### ISSUE TITLE
Arithmetic overflow on migration

### ISSUE THREAD

**Issue by MattA48** [gottscj/Hangfire.Mongo#399] opened 2024-05-28 14:55 UTC
Getting a reproducible exception on trying to run an update to 1.9.16 with a drop migration strategy

The callstack etc is below.

The environment we're running in is k8s with 6 pods of this app running, but also 3 of a similar app also using running the same Hangfire jobs on the same db. I assume this shouldn't be an issue and the relevant locks should still work.

{"@timestamp":"2024-05-28T13:49:57.4347774Z", "fields":{"TimeStamp":"2024-05-28T13:49:57.4347774Z","Message":"Executed migration step: CreateIndexes[1] in 399ms","Level":"Information","ClassName":"Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy","MachineName":"subscriber-bff-pricing-78798c6468-qt5fj","SecurityContext":"root","Component":"Bff","Environment":"prod","Service":"Bff.Api","Source":"Pricing"}}
Unhandled exception. Hangfire.Mongo.Migration.MongoMigrationException: Migration failed in Hangfire.Mongo.Migration.Steps.Version13.SumCounters
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Int64.System.Numerics.IAdditionOperators<System.Int64,System.Int64,System.Int64>.op_CheckedAddition(Int64 left, Int64 right)
   at System.Linq.Enumerable.Sum[TSource,TResult,TAccumulator](IEnumerable`1 source, Func`2 selector)
   at Hangfire.Mongo.Migration.Steps.Version13.SumCounters.Execute(IMongoDatabase database, MongoStorageOptions storageOptions, IMongoMigrationContext migrationContext)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   --- End of inner exception stack trace ---
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.DropMongoMigrationStrategy.ExecuteMigration(IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategy.Execute(MongoStorageOptions storageOptions, IMongoDatabase database, MongoSchema fromSchema, MongoSchema toSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate(MongoBackupStrategy backupStrategy, MongoMigrationStrategy migrationStrategy)
   at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(MongoStorageOptions storageOptions, IMongoDatabase database)
   at Hangfire.Mongo.MongoStorage..ctor(IMongoClient mongoClient, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoStorage..ctor(MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, MongoClientSettings mongoClientSettings, String databaseName, MongoStorageOptions storageOptions)
   at Hangfire.Mongo.MongoBootstrapperConfigurationExtensions.UseMongoStorage(IGlobalConfiguration configuration, String connectionString, MongoStorageOptions storageOptions)
   at Icis.Pricing.Bff.Infrastructure.Startup.<ConfigureServices>b__7_0(IGlobalConfiguration configuration) in /build/src/main/Bff/Infrastructure/Startup.cs:line 100
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass0_0.<AddHangfire>b__0(IServiceProvider provider, IGlobalConfiguration config) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 40
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass1_0.<AddHangfire>b__14(IServiceProvider serviceProvider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 103
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Hangfire.HangfireServiceCollectionExtensions.ThrowIfNotConfigured(IServiceProvider serviceProvider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 307
   at Hangfire.HangfireServiceCollectionExtensions.CreateBackgroundJobServerHostedService(IServiceProvider provider, JobStorage storage, IEnumerable`1 additionalProcesses, BackgroundJobServerOptions options) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 241
   at Hangfire.HangfireServiceCollectionExtensions.<>c__DisplayClass9_0.<AddHangfireServerInner>b__0(IServiceProvider provider) in C:\projects\hangfire-525\src\Hangfire.NetCore\HangfireServiceCollectionExtensions.cs:line 194
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
... other non-hangfire specific calls

**Comment by gottscj** [comment] 2024-05-28 17:30
@MattA48,

Is your target version 1.9.16? 

Can you elaborate on your hangfire.mongo configuration, other than you are using DropStrategy?

thanks

**Comment by MattA48** [comment] 2024-05-29 09:41
Hi @gottscj - yes, this migration is due to an update to Hangfire.Mongo to 1.9.16 from 1.7.2. It is also updating Hangfire.AspNetCore from 1.7.30 to 1.8.9

Our hangfire.mongo config isn't too complex - 

                   .UseMongoStorage(
                        this.configuration.GetMongoUrl().ToString(), //I'm guessing you don't need our Mongo connection string
                        new MongoStorageOptions
                        {
                            MigrationOptions = new MongoMigrationOptions
                            {
                                MigrationStrategy = new DropMongoMigrationStrategy()
                            },
                            Prefix = "hangfire.mongo_2",
                            CheckConnection = true
                        }));
                        
We're hoping to bypass this problem for now (as we only see it in our prod system - our test systems didn't have an issue updating) by adding the _2 suffix to the prefix.

**Comment by gottscj** [comment] 2024-05-29 19:24
@MattA48,

I cannot reproduce locally. I am not using a k8s setup though. You are stopping all pods connected to the database? 
Running migrations are isolated using a specific distributed lock for migrations. it is a single document in the "hangfire.migrationLock" collection.

**Comment by MattA48** [comment] 2024-06-03 08:39
Really sorry - I'm sure I wrote a response to this several days ago, but must have forgotten to commit the comment

So the k8s upgrade will progressively halt pods while upgrade pods are being created to ensure no downtime, so we have 6 pods running, so it will take spin up 2 upgraded, take down 2 old when they're up and ready, then move onto another 2 until all 6 are upgraded. This means there will be some period where old and new are both running. I had been assuming the lock would have handled this?

**Comment by gottscj** [comment] 2024-06-03 14:53
@MattA48,

The migration lock only isolates the migration itself meaning no instances will run _migrations_ simultaneously. 
You must stop the entire system while migrating. also running different versions of hangfire with different schema version is not supported.

There is no guarantee one pod is actively processing a job while the migration runs, that job and its status will most definitely be lost or corrupt.

if your requirements cannot accept downtime, you could migrate the updated pods to a new database targeting the new schema. however, there is no guarantee all jobs scheduled or processing defined in the old database are finalized.

**Comment by gottscj** [comment] 2024-06-05 08:24
@MattA48,

Do you have any progress on this?

Thanks

**Comment by MattA48** [comment] 2024-06-05 21:39
We went around it by using a new prefix - we need to maintain a service as always-up and this seemed the easiest way to do it. It's not important for us to run our background tasks at exact intervals - we only use hangfire so that we don't run our periodic background tasks once per replica, so keeping exact timings aren't so important

**Comment by gottscj** [comment] 2024-06-06 18:59
@MattA48,

Thanks for posting your solution. closing

**Closed by gottscj** 2024-06-06 18:59 UTC
