### ISSUE TITLE
Job Distribution not Happening During Scale Down

### ISSUE THREAD

**Issue by dwevedivaibhav** [gottscj/Hangfire.Mongo#388] opened 2024-03-16 12:57 UTC
Hi @gottscj 

I have an additional Issue related to processing background jobs in different workers within the Hangfire server.

1. To illustrate, let's consider scheduling 20 background jobs across 3 containers, each with 2GB CPU and 4GB Memory. During distribution, everything works seamlessly. However, when the server crashes or scales down and a new server is brought up, Hangfire resumes distributing jobs. I've noticed a glitch: if one container (Hangfire server worker) initially receives 10 jobs, subsequent jobs are not allocated to other servers until the earlier allocated 10 jobs are processed. Meanwhile, other servers with fewer or no jobs continue to remain idle.

2. During server crashes and the subsequent replacement with a new server, I've noticed that jobs are migrating from one server to another, despite the presence of a lock. This migration includes jobs that were originally running on servers that didn't experience crashes.

Could you provide insights into addressing this issue or optimizing the job distribution process?

Thank you for your assistance!

**Comment by gottscj** [comment] 2024-03-17 12:56
@dwevedivaibhav,

Im guessing you each container has a 2 logical cores. Else im not sure what you mean with 2GB CPU. :)
Hangfire will per default allocate 5 worker threads per logical core.

`WorkerCount = Math.Min(Environment.ProcessorCount * 5, MaxDefaultWorkerCount);`
You can read more about it in the hangfire documentation:
https://docs.hangfire.io/en/latest/background-processing/configuring-degree-of-parallelism.html

This would explain what you are seeing in 1.

for item 2, I would need a lot more info on your setup, logs and potentially a JSON dump of your hangfire.mongo database in order to help.

I hope this helps.
Thanks

**Comment by dwevedivaibhav** [comment] 2024-03-19 03:49
Hi @gottscj,

Thank you for your clarification.

1. Indeed, the formula for CPU cores is well understood. To address the issue at hand, let's delve into the scenario with three servers, each running 10 worker counts. Under normal conditions, we can schedule up to 30 background jobs in parallel, with each server capable of handling 10.

The challenge arises when a server crashes or scales down, and a new server is spun up. Despite implementing Hangfire's job distribution mechanism, there appears to be an anomaly. If one container initially receives 10 jobs, subsequent jobs aren't distributed to other servers until the first set of 10 jobs is processed. This results in underutilization of resources, with other servers remaining idle despite having available capacity.

It seems that there's an issue with job distribution during server crashes. Let's explore this further to identify the root cause and implement a solution to ensure optimal resource utilization and job distribution across servers.


2. Let's delve into the second question which is addition of first question.

In a simple scenario with three servers (A, B, and C), each running one job (Job 1, Job 2, and Job 3, respectively), the initial execution and distribution seem to function correctly. However, when Server A crashes and a new Server D is brought up, an unexpected behavior occurs. Occasionally, Job 2 from Server B migrates to Server D, even though a distribution lock has been implemented. Ideally, only Job 1 from Server A should be reassigned to Server D.

This unexpected migration of jobs is causing duplicates and disrupting the system's operation. We need to investigate why Job 2 from Server B is being erroneously reassigned to Server D and implement a solution to ensure accurate job distribution and prevent duplicates.

I appreciate your attention to this matter and look forward to your insights on resolving this issue.

Thanks

**Comment by dwevedivaibhav** [comment] 2024-03-28 04:29
Hi @gottscj,
Any update on this ?

**Comment by gottscj** [comment] 2024-03-31 08:04
@dwevedivaibhav,

I have been on vacation.
While your highlevel description gives context, I cannot help without more information.
Please provide detailed information about
1. your configured mongoOptions
2. you configured hangfire options
3. logs with TRACE level
4. if you privacy allows, a JSON dump of your hangfire.mongo database

if you could create simple application which could reproduce the issue, that would also be very helpful.

Thanks!

**Comment by gottscj** [comment] 2024-04-16 17:50
@dwevedivaibhav,

Would it be possible to provide more insight?

Thanks

**Comment by dwevedivaibhav** [comment] 2024-04-18 03:59
Hi @gottscj ,

I apologize for the delayed response. I wanted to bring to your attention a challenge we're facing with our workflow scheduling using the Elsa framework and Hangfire Mongo.

We're utilizing Elsa for creating workflows and scheduling background jobs. However, to distribute these jobs across multiple servers, we've implemented Hangfire Mongo. The issue arises when we attempt to schedule multiple jobs in parallel. For instance, let's say we schedule 30 jobs in parallel, with each server capable of handling 10.

The challenge manifests when a server crashes or scales down, prompting the spin-up of a new server. Despite implementing Hangfire's job distribution mechanism, we've encountered an anomaly. If one container initially receives 10 jobs, subsequent jobs aren't distributed to other servers until the first set of 10 jobs is processed. This leads to underutilization of resources, with other servers remaining idle despite available capacity.

let me give how i configured hangfire in start up

 var migrationOptions = new MongoMigrationOptions
            {
                MigrationStrategy = new MigrateMongoMigrationStrategy(),
                BackupStrategy = new CollectionMongoBackupStrategy()

            };
            var storageOptions = new MongoStorageOptions
            {
                MigrationOptions = migrationOptions,
                CheckConnection = false
            };
            services.AddHangfire(configuration => configuration
           .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
           .UseSimpleAssemblyNameTypeSerializer()
           .UseRecommendedSerializerSettings(settings => settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb))
           .UseMongoStorage(mongoDatabaseOptions?.ConnectionString + "/" + mongoDatabaseOptions?.DatabaseName, storageOptions));
            services.AddHangfireServer((sp, options) =>
            {
                options.HeartbeatInterval = TimeSpan.FromSeconds(2);
                options.ConfigureForElsaDispatchers(sp);
            });

We're currently exploring potential solutions to address this issue and ensure optimal resource utilization across all servers. Your expertise and insights on this matter would be greatly appreciated.

let me know if you need more details on this

Thank you for your attention to this concern.

**Comment by gottscj** [comment] 2024-04-24 18:54
@dwevedivaibhav,

I still need more information as addressed in earlier comments. Else I simply cannot help. ¯\_(ツ)_/¯

**Comment by gottscj** [comment] 2024-05-20 18:29
closing due to inactivity

**Closed by gottscj** 2024-05-20 18:29 UTC
